const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: 'images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: 'images/p1.jpg',
      price: 320,
      countInStock: 4,
      brand: 'Adidas',
      rating: 3,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Arrow Slim Shirt',
      category: 'Shirts',
      image: 'images/p1.jpg',
      price: 120,
      countInStock: 30,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: 'images/p1.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: 'images/p1.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: 'images/p1.jpg',
      price: 120,
      countInStock: 6,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
